---
- hosts: all
  become: true
  tasks:



  - name: remove apache2 and php  package
    apt:
      name: 
        - apache2
        - php
      state: absent
      update_cache: no
    when: ansible_distribution == "Ubuntu"
  

  - name: remove apache2 and php package
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"

